export default {
    defaultTheme: "light",
    themes: {
        light: {
            dark: false,
            colors: {
                background: "#E6EAF2",
                surface: "#FBFCFF",
                "on-surface": "#1C1B1F",
                onSurface: "#1C1B1F",
                "surface-variant": "#E6EAF2",
                "on-surface-variant": "#79747E",
                onSurfaceVariant: "#79747E",
                primary: "#002C5F",
                "on-primary": "#FFFCFE",
                secondary: "#3489C6",
                error: "#B3261E",
                "on-error": "#FFFCFE",
                info: "#45474F",
                success: "#3CC13B",
                warning: "#F3AA1C",
                "on-warning": "#FFFCFE",
                selected: "#DCEAF5",
            },
        },
        dark: {
            dark: true,
            colors: {
                background: "#191922",
                surface: "#25282f",
                "on-surface": "#FFFCFE",
                onSurface: "#FFFCFE",
                "surface-variant": "#191922",
                "on-surface-variant": "#C4C8D0",
                "surface-bright": "#FBFCFF",
                "on-surface-bright": "#1C1B1F",
                onSurfaceVariant: "#C4C8D0",
                primary: "#6E89B3",
                "on-primary": "#002C5F",
                secondary: "#DCEAF5",
                error: "#F2B8B5",
                "on-error": "#B3261E",
                info: "#C0C3CC",
                success: "#A5E0A2",
                warning: "#F9DB84",
                "on-warning": "#F3AA1C",
                selected: "#444758",
            },
        },
    },
};
