export default {
    datetime: "2024/05/12일 20:06:13",
    returnCode: 0,
    returnMessage: "Success",
    data: [
        {
            role_auth_id: null,
            role_id: null,
            menu_cd: "RMSM000002",
            screenUse: "Y",
            upmenu_cd: null,
            iq_auth_yn: "Y",
            mdfy_auth_yn: "N",
            sav_auth_yn: "N",
            del_auth_yn: "N",
            oput_auth_yn: "N",
            excl_auth_yn: "N",
            upld_auth_yn: "N",
            dnl_auth_yn: null,
            pgm_path_adr: null,
            reg_user_id: null,
            reg_dt: null,
            modi_user_id: null,
            modi_dt: null,
            shop_cd: null,
            shop_tcd: null,
            reg_user_nm: null,
            modi_user_nm: null,
            menu_nm: "시스템",
            level_no: 2,
            scrn_yn: null,
            supi_menu_cd: "RMSM000001",
            supi_menu_cd_nm: "전체 샵 적용",
            supi_menu_nm: null,
            childList: [
                {
                    role_auth_id: null,
                    role_id: null,
                    menu_cd: "RMSM000003",
                    screenUse: "Y",
                    upmenu_cd: null,
                    iq_auth_yn: "Y",
                    mdfy_auth_yn: "N",
                    sav_auth_yn: "N",
                    del_auth_yn: "N",
                    oput_auth_yn: "N",
                    excl_auth_yn: "N",
                    upld_auth_yn: "N",
                    dnl_auth_yn: null,
                    pgm_path_adr: null,
                    reg_user_id: null,
                    reg_dt: null,
                    modi_user_id: null,
                    modi_dt: null,
                    shop_cd: null,
                    shop_tcd: null,
                    reg_user_nm: null,
                    modi_user_nm: null,
                    menu_nm: "시스템 관리",
                    level_no: 3,
                    scrn_yn: null,
                    supi_menu_cd: "RMSM000002",
                    supi_menu_cd_nm: "시스템",
                    supi_menu_nm: null,
                    childList: [
                        {
                            role_auth_id: null,
                            role_id: null,
                            menu_cd: "RMSM000252",
                            screenUse: "N",
                            upmenu_cd: null,
                            iq_auth_yn: "N",
                            mdfy_auth_yn: "N",
                            sav_auth_yn: "N",
                            del_auth_yn: "N",
                            oput_auth_yn: "N",
                            excl_auth_yn: "N",
                            upld_auth_yn: "N",
                            dnl_auth_yn: null,
                            pgm_path_adr: null,
                            reg_user_id: null,
                            reg_dt: null,
                            modi_user_id: null,
                            modi_dt: null,
                            shop_cd: null,
                            shop_tcd: null,
                            reg_user_nm: null,
                            modi_user_nm: null,
                            menu_nm: "공장 그룹관리",
                            level_no: 4,
                            scrn_yn: null,
                            supi_menu_cd: "RMSM000003",
                            supi_menu_cd_nm: "시스템 관리",
                            supi_menu_nm: null,
                            childList: null,
                        },
                        {
                            role_auth_id: null,
                            role_id: null,
                            menu_cd: "RMSM000011",
                            screenUse: "Y",
                            upmenu_cd: null,
                            iq_auth_yn: "Y",
                            mdfy_auth_yn: "Y",
                            sav_auth_yn: "Y",
                            del_auth_yn: "Y",
                            oput_auth_yn: "Y",
                            excl_auth_yn: "Y",
                            upld_auth_yn: "Y",
                            dnl_auth_yn: null,
                            pgm_path_adr: "/all/system/system/management",
                            reg_user_id: null,
                            reg_dt: null,
                            modi_user_id: null,
                            modi_dt: null,
                            shop_cd: null,
                            shop_tcd: null,
                            reg_user_nm: null,
                            modi_user_nm: null,
                            menu_nm: "공장 관리",
                            level_no: 4,
                            scrn_yn: null,
                            supi_menu_cd: "RMSM000003",
                            supi_menu_cd_nm: "시스템 관리",
                            supi_menu_nm: null,
                            childList: null,
                        },
                    ],
                },
                {
                    role_auth_id: null,
                    role_id: null,
                    menu_cd: "RMSM000004",
                    screenUse: "Y",
                    upmenu_cd: null,
                    iq_auth_yn: "Y",
                    mdfy_auth_yn: "N",
                    sav_auth_yn: "N",
                    del_auth_yn: "N",
                    oput_auth_yn: "N",
                    excl_auth_yn: "N",
                    upld_auth_yn: "N",
                    dnl_auth_yn: null,
                    pgm_path_adr: null,
                    reg_user_id: null,
                    reg_dt: null,
                    modi_user_id: null,
                    modi_dt: null,
                    shop_cd: null,
                    shop_tcd: null,
                    reg_user_nm: null,
                    modi_user_nm: null,
                    menu_nm: "사용자 관리",
                    level_no: 3,
                    scrn_yn: null,
                    supi_menu_cd: "RMSM000002",
                    supi_menu_cd_nm: "시스템",
                    supi_menu_nm: null,
                    childList: [
                        {
                            role_auth_id: null,
                            role_id: null,
                            menu_cd: "RMSM000012",
                            screenUse: "Y",
                            upmenu_cd: null,
                            iq_auth_yn: "Y",
                            mdfy_auth_yn: "Y",
                            sav_auth_yn: "Y",
                            del_auth_yn: "Y",
                            oput_auth_yn: "Y",
                            excl_auth_yn: "Y",
                            upld_auth_yn: "Y",
                            dnl_auth_yn: null,
                            pgm_path_adr: "/all/system/auth/management",
                            reg_user_id: null,
                            reg_dt: null,
                            modi_user_id: null,
                            modi_dt: null,
                            shop_cd: null,
                            shop_tcd: null,
                            reg_user_nm: null,
                            modi_user_nm: null,
                            menu_nm: "권한 관리",
                            level_no: 4,
                            scrn_yn: null,
                            supi_menu_cd: "RMSM000004",
                            supi_menu_cd_nm: "사용자 관리",
                            supi_menu_nm: null,
                            childList: null,
                        },
                        {
                            role_auth_id: null,
                            role_id: null,
                            menu_cd: "RMSM000013",
                            screenUse: "Y",
                            upmenu_cd: null,
                            iq_auth_yn: "Y",
                            mdfy_auth_yn: "Y",
                            sav_auth_yn: "Y",
                            del_auth_yn: "Y",
                            oput_auth_yn: "Y",
                            excl_auth_yn: "Y",
                            upld_auth_yn: "Y",
                            dnl_auth_yn: null,
                            pgm_path_adr: "/all/system/auth/revoked",
                            reg_user_id: null,
                            reg_dt: null,
                            modi_user_id: null,
                            modi_dt: null,
                            shop_cd: null,
                            shop_tcd: null,
                            reg_user_nm: null,
                            modi_user_nm: null,
                            menu_nm: "권한 회수 조회",
                            level_no: 4,
                            scrn_yn: null,
                            supi_menu_cd: "RMSM000004",
                            supi_menu_cd_nm: "사용자 관리",
                            supi_menu_nm: null,
                            childList: null,
                        },
                        {
                            role_auth_id: null,
                            role_id: null,
                            menu_cd: "RMSM000014",
                            screenUse: "Y",
                            upmenu_cd: null,
                            iq_auth_yn: "Y",
                            mdfy_auth_yn: "Y",
                            sav_auth_yn: "Y",
                            del_auth_yn: "Y",
                            oput_auth_yn: "Y",
                            excl_auth_yn: "Y",
                            upld_auth_yn: "Y",
                            dnl_auth_yn: null,
                            pgm_path_adr: "/all/system/auth/grant",
                            reg_user_id: null,
                            reg_dt: null,
                            modi_user_id: null,
                            modi_dt: null,
                            shop_cd: null,
                            shop_tcd: null,
                            reg_user_nm: null,
                            modi_user_nm: null,
                            menu_nm: "시스템 권한 부여",
                            level_no: 4,
                            scrn_yn: null,
                            supi_menu_cd: "RMSM000004",
                            supi_menu_cd_nm: "사용자 관리",
                            supi_menu_nm: null,
                            childList: null,
                        },
                        {
                            role_auth_id: null,
                            role_id: null,
                            menu_cd: "RMSM000015",
                            screenUse: "Y",
                            upmenu_cd: null,
                            iq_auth_yn: "Y",
                            mdfy_auth_yn: "Y",
                            sav_auth_yn: "Y",
                            del_auth_yn: "Y",
                            oput_auth_yn: "Y",
                            excl_auth_yn: "Y",
                            upld_auth_yn: "Y",
                            dnl_auth_yn: null,
                            pgm_path_adr: "/all/system/auth/unit",
                            reg_user_id: null,
                            reg_dt: null,
                            modi_user_id: null,
                            modi_dt: null,
                            shop_cd: null,
                            shop_tcd: null,
                            reg_user_nm: null,
                            modi_user_nm: null,
                            menu_nm: "단위 업무 권한 조회",
                            level_no: 4,
                            scrn_yn: null,
                            supi_menu_cd: "RMSM000004",
                            supi_menu_cd_nm: "사용자 관리",
                            supi_menu_nm: null,
                            childList: null,
                        },
                        {
                            role_auth_id: null,
                            role_id: null,
                            menu_cd: "RMSM000131",
                            screenUse: "Y",
                            upmenu_cd: null,
                            iq_auth_yn: "Y",
                            mdfy_auth_yn: "Y",
                            sav_auth_yn: "Y",
                            del_auth_yn: "Y",
                            oput_auth_yn: "N",
                            excl_auth_yn: "Y",
                            upld_auth_yn: "Y",
                            dnl_auth_yn: null,
                            pgm_path_adr: "/all/system/auth/password",
                            reg_user_id: null,
                            reg_dt: null,
                            modi_user_id: null,
                            modi_dt: null,
                            shop_cd: null,
                            shop_tcd: null,
                            reg_user_nm: null,
                            modi_user_nm: null,
                            menu_nm: "사용자 관리",
                            level_no: 4,
                            scrn_yn: null,
                            supi_menu_cd: "RMSM000004",
                            supi_menu_cd_nm: "사용자 관리",
                            supi_menu_nm: null,
                            childList: null,
                        },
                    ],
                },
                {
                    role_auth_id: null,
                    role_id: null,
                    menu_cd: "RMSM000005",
                    screenUse: "Y",
                    upmenu_cd: null,
                    iq_auth_yn: "Y",
                    mdfy_auth_yn: "N",
                    sav_auth_yn: "N",
                    del_auth_yn: "N",
                    oput_auth_yn: "N",
                    excl_auth_yn: "N",
                    upld_auth_yn: "N",
                    dnl_auth_yn: null,
                    pgm_path_adr: null,
                    reg_user_id: null,
                    reg_dt: null,
                    modi_user_id: null,
                    modi_dt: null,
                    shop_cd: null,
                    shop_tcd: null,
                    reg_user_nm: null,
                    modi_user_nm: null,
                    menu_nm: "코드 관리",
                    level_no: 3,
                    scrn_yn: null,
                    supi_menu_cd: "RMSM000002",
                    supi_menu_cd_nm: "시스템",
                    supi_menu_nm: null,
                    childList: [
                        {
                            role_auth_id: null,
                            role_id: null,
                            menu_cd: "RMSM000016",
                            screenUse: "Y",
                            upmenu_cd: null,
                            iq_auth_yn: "Y",
                            mdfy_auth_yn: "Y",
                            sav_auth_yn: "Y",
                            del_auth_yn: "Y",
                            oput_auth_yn: "Y",
                            excl_auth_yn: "Y",
                            upld_auth_yn: "Y",
                            dnl_auth_yn: null,
                            pgm_path_adr: "/all/system/code/common",
                            reg_user_id: null,
                            reg_dt: null,
                            modi_user_id: null,
                            modi_dt: null,
                            shop_cd: null,
                            shop_tcd: null,
                            reg_user_nm: null,
                            modi_user_nm: null,
                            menu_nm: "공통 코드 관리",
                            level_no: 4,
                            scrn_yn: null,
                            supi_menu_cd: "RMSM000005",
                            supi_menu_cd_nm: "코드 관리",
                            supi_menu_nm: null,
                            childList: null,
                        },
                        {
                            role_auth_id: null,
                            role_id: null,
                            menu_cd: "RMSM000017",
                            screenUse: "Y",
                            upmenu_cd: null,
                            iq_auth_yn: "Y",
                            mdfy_auth_yn: "Y",
                            sav_auth_yn: "Y",
                            del_auth_yn: "Y",
                            oput_auth_yn: "Y",
                            excl_auth_yn: "Y",
                            upld_auth_yn: "Y",
                            dnl_auth_yn: null,
                            pgm_path_adr: "/all/system/code/message",
                            reg_user_id: null,
                            reg_dt: null,
                            modi_user_id: null,
                            modi_dt: null,
                            shop_cd: null,
                            shop_tcd: null,
                            reg_user_nm: null,
                            modi_user_nm: null,
                            menu_nm: "메시지 관리",
                            level_no: 4,
                            scrn_yn: null,
                            supi_menu_cd: "RMSM000005",
                            supi_menu_cd_nm: "코드 관리",
                            supi_menu_nm: null,
                            childList: null,
                        },
                    ],
                },
                {
                    role_auth_id: null,
                    role_id: null,
                    menu_cd: "RMSM000006",
                    screenUse: "Y",
                    upmenu_cd: null,
                    iq_auth_yn: "Y",
                    mdfy_auth_yn: "N",
                    sav_auth_yn: "N",
                    del_auth_yn: "N",
                    oput_auth_yn: "N",
                    excl_auth_yn: "N",
                    upld_auth_yn: "N",
                    dnl_auth_yn: null,
                    pgm_path_adr: null,
                    reg_user_id: null,
                    reg_dt: null,
                    modi_user_id: null,
                    modi_dt: null,
                    shop_cd: null,
                    shop_tcd: null,
                    reg_user_nm: null,
                    modi_user_nm: null,
                    menu_nm: "메뉴 관리",
                    level_no: 3,
                    scrn_yn: null,
                    supi_menu_cd: "RMSM000002",
                    supi_menu_cd_nm: "시스템",
                    supi_menu_nm: null,
                    childList: [
                        {
                            role_auth_id: null,
                            role_id: null,
                            menu_cd: "RMSM000019",
                            screenUse: "Y",
                            upmenu_cd: null,
                            iq_auth_yn: "Y",
                            mdfy_auth_yn: "Y",
                            sav_auth_yn: "Y",
                            del_auth_yn: "Y",
                            oput_auth_yn: "Y",
                            excl_auth_yn: "Y",
                            upld_auth_yn: "Y",
                            dnl_auth_yn: null,
                            pgm_path_adr: "/all/system/menu/management",
                            reg_user_id: null,
                            reg_dt: null,
                            modi_user_id: null,
                            modi_dt: null,
                            shop_cd: null,
                            shop_tcd: null,
                            reg_user_nm: null,
                            modi_user_nm: null,
                            menu_nm: "메뉴 관리",
                            level_no: 4,
                            scrn_yn: null,
                            supi_menu_cd: "RMSM000006",
                            supi_menu_cd_nm: "메뉴 관리",
                            supi_menu_nm: null,
                            childList: null,
                        },
                    ],
                },
                {
                    role_auth_id: null,
                    role_id: null,
                    menu_cd: "RMSM000007",
                    screenUse: "Y",
                    upmenu_cd: null,
                    iq_auth_yn: "Y",
                    mdfy_auth_yn: "N",
                    sav_auth_yn: "N",
                    del_auth_yn: "N",
                    oput_auth_yn: "N",
                    excl_auth_yn: "N",
                    upld_auth_yn: "N",
                    dnl_auth_yn: null,
                    pgm_path_adr: null,
                    reg_user_id: null,
                    reg_dt: null,
                    modi_user_id: null,
                    modi_dt: null,
                    shop_cd: null,
                    shop_tcd: null,
                    reg_user_nm: null,
                    modi_user_nm: null,
                    menu_nm: "프로그램 관리",
                    level_no: 3,
                    scrn_yn: null,
                    supi_menu_cd: "RMSM000002",
                    supi_menu_cd_nm: "시스템",
                    supi_menu_nm: null,
                    childList: [
                        {
                            role_auth_id: null,
                            role_id: null,
                            menu_cd: "RMSM000020",
                            screenUse: "Y",
                            upmenu_cd: null,
                            iq_auth_yn: "Y",
                            mdfy_auth_yn: "Y",
                            sav_auth_yn: "Y",
                            del_auth_yn: "Y",
                            oput_auth_yn: "Y",
                            excl_auth_yn: "Y",
                            upld_auth_yn: "Y",
                            dnl_auth_yn: null,
                            pgm_path_adr: "/all/system/program/management",
                            reg_user_id: null,
                            reg_dt: null,
                            modi_user_id: null,
                            modi_dt: null,
                            shop_cd: null,
                            shop_tcd: null,
                            reg_user_nm: null,
                            modi_user_nm: null,
                            menu_nm: "프로그램 관리",
                            level_no: 4,
                            scrn_yn: null,
                            supi_menu_cd: "RMSM000007",
                            supi_menu_cd_nm: "프로그램 관리",
                            supi_menu_nm: null,
                            childList: null,
                        },
                    ],
                },
                {
                    role_auth_id: null,
                    role_id: null,
                    menu_cd: "RMSM000008",
                    screenUse: "Y",
                    upmenu_cd: null,
                    iq_auth_yn: "Y",
                    mdfy_auth_yn: "N",
                    sav_auth_yn: "N",
                    del_auth_yn: "N",
                    oput_auth_yn: "N",
                    excl_auth_yn: "N",
                    upld_auth_yn: "N",
                    dnl_auth_yn: null,
                    pgm_path_adr: null,
                    reg_user_id: null,
                    reg_dt: null,
                    modi_user_id: null,
                    modi_dt: null,
                    shop_cd: null,
                    shop_tcd: null,
                    reg_user_nm: null,
                    modi_user_nm: null,
                    menu_nm: "역할 관리",
                    level_no: 3,
                    scrn_yn: null,
                    supi_menu_cd: "RMSM000002",
                    supi_menu_cd_nm: "시스템",
                    supi_menu_nm: null,
                    childList: [
                        {
                            role_auth_id: null,
                            role_id: null,
                            menu_cd: "RMSM000022",
                            screenUse: "Y",
                            upmenu_cd: null,
                            iq_auth_yn: "Y",
                            mdfy_auth_yn: "Y",
                            sav_auth_yn: "Y",
                            del_auth_yn: "Y",
                            oput_auth_yn: "Y",
                            excl_auth_yn: "Y",
                            upld_auth_yn: "Y",
                            dnl_auth_yn: null,
                            pgm_path_adr: "/all/system/role/management",
                            reg_user_id: null,
                            reg_dt: null,
                            modi_user_id: null,
                            modi_dt: null,
                            shop_cd: null,
                            shop_tcd: null,
                            reg_user_nm: null,
                            modi_user_nm: null,
                            menu_nm: "역할 관리",
                            level_no: 4,
                            scrn_yn: null,
                            supi_menu_cd: "RMSM000008",
                            supi_menu_cd_nm: "역할 관리",
                            supi_menu_nm: null,
                            childList: null,
                        },
                        {
                            role_auth_id: null,
                            role_id: null,
                            menu_cd: "RMSM000023",
                            screenUse: "Y",
                            upmenu_cd: null,
                            iq_auth_yn: "Y",
                            mdfy_auth_yn: "Y",
                            sav_auth_yn: "Y",
                            del_auth_yn: "Y",
                            oput_auth_yn: "Y",
                            excl_auth_yn: "Y",
                            upld_auth_yn: "Y",
                            dnl_auth_yn: null,
                            pgm_path_adr: "/all/system/role/menu-by-role",
                            reg_user_id: null,
                            reg_dt: null,
                            modi_user_id: null,
                            modi_dt: null,
                            shop_cd: null,
                            shop_tcd: null,
                            reg_user_nm: null,
                            modi_user_nm: null,
                            menu_nm: "역할 별 메뉴 관리",
                            level_no: 4,
                            scrn_yn: null,
                            supi_menu_cd: "RMSM000008",
                            supi_menu_cd_nm: "역할 관리",
                            supi_menu_nm: null,
                            childList: null,
                        },
                    ],
                },
                {
                    role_auth_id: null,
                    role_id: null,
                    menu_cd: "RMSM000009",
                    screenUse: "Y",
                    upmenu_cd: null,
                    iq_auth_yn: "Y",
                    mdfy_auth_yn: "N",
                    sav_auth_yn: "N",
                    del_auth_yn: "N",
                    oput_auth_yn: "N",
                    excl_auth_yn: "N",
                    upld_auth_yn: "N",
                    dnl_auth_yn: null,
                    pgm_path_adr: null,
                    reg_user_id: null,
                    reg_dt: null,
                    modi_user_id: null,
                    modi_dt: null,
                    shop_cd: null,
                    shop_tcd: null,
                    reg_user_nm: null,
                    modi_user_nm: null,
                    menu_nm: "로그 관리",
                    level_no: 3,
                    scrn_yn: null,
                    supi_menu_cd: "RMSM000002",
                    supi_menu_cd_nm: "시스템",
                    supi_menu_nm: null,
                    childList: [
                        {
                            role_auth_id: null,
                            role_id: null,
                            menu_cd: "RMSM000025",
                            screenUse: "Y",
                            upmenu_cd: null,
                            iq_auth_yn: "Y",
                            mdfy_auth_yn: "Y",
                            sav_auth_yn: "Y",
                            del_auth_yn: "Y",
                            oput_auth_yn: "Y",
                            excl_auth_yn: "Y",
                            upld_auth_yn: "Y",
                            dnl_auth_yn: null,
                            pgm_path_adr: "/all/system/log/use",
                            reg_user_id: null,
                            reg_dt: null,
                            modi_user_id: null,
                            modi_dt: null,
                            shop_cd: null,
                            shop_tcd: null,
                            reg_user_nm: null,
                            modi_user_nm: null,
                            menu_nm: "사용로그 조회",
                            level_no: 4,
                            scrn_yn: null,
                            supi_menu_cd: "RMSM000009",
                            supi_menu_cd_nm: "로그 관리",
                            supi_menu_nm: null,
                            childList: null,
                        },
                        {
                            role_auth_id: null,
                            role_id: null,
                            menu_cd: "RMSM000130",
                            screenUse: "Y",
                            upmenu_cd: null,
                            iq_auth_yn: "Y",
                            mdfy_auth_yn: "N",
                            sav_auth_yn: "N",
                            del_auth_yn: "N",
                            oput_auth_yn: "N",
                            excl_auth_yn: "N",
                            upld_auth_yn: "N",
                            dnl_auth_yn: null,
                            pgm_path_adr: "/all/system/log/access",
                            reg_user_id: null,
                            reg_dt: null,
                            modi_user_id: null,
                            modi_dt: null,
                            shop_cd: null,
                            shop_tcd: null,
                            reg_user_nm: null,
                            modi_user_nm: null,
                            menu_nm: "접속로그 조회",
                            level_no: 4,
                            scrn_yn: null,
                            supi_menu_cd: "RMSM000009",
                            supi_menu_cd_nm: "로그 관리",
                            supi_menu_nm: null,
                            childList: null,
                        },
                    ],
                },
                {
                    role_auth_id: null,
                    role_id: null,
                    menu_cd: "RMSM000010",
                    screenUse: "Y",
                    upmenu_cd: null,
                    iq_auth_yn: "Y",
                    mdfy_auth_yn: "N",
                    sav_auth_yn: "N",
                    del_auth_yn: "N",
                    oput_auth_yn: "N",
                    excl_auth_yn: "N",
                    upld_auth_yn: "N",
                    dnl_auth_yn: null,
                    pgm_path_adr: null,
                    reg_user_id: null,
                    reg_dt: null,
                    modi_user_id: null,
                    modi_dt: null,
                    shop_cd: null,
                    shop_tcd: null,
                    reg_user_nm: null,
                    modi_user_nm: null,
                    menu_nm: "기타 관리",
                    level_no: 3,
                    scrn_yn: null,
                    supi_menu_cd: "RMSM000002",
                    supi_menu_cd_nm: "시스템",
                    supi_menu_nm: null,
                    childList: [
                        {
                            role_auth_id: null,
                            role_id: null,
                            menu_cd: "RMSM000029",
                            screenUse: "Y",
                            upmenu_cd: null,
                            iq_auth_yn: "Y",
                            mdfy_auth_yn: "Y",
                            sav_auth_yn: "Y",
                            del_auth_yn: "Y",
                            oput_auth_yn: "Y",
                            excl_auth_yn: "Y",
                            upld_auth_yn: "Y",
                            dnl_auth_yn: null,
                            pgm_path_adr: "/all/system/other/mail/history",
                            reg_user_id: null,
                            reg_dt: null,
                            modi_user_id: null,
                            modi_dt: null,
                            shop_cd: null,
                            shop_tcd: null,
                            reg_user_nm: null,
                            modi_user_nm: null,
                            menu_nm: "메일 발송 이력",
                            level_no: 4,
                            scrn_yn: null,
                            supi_menu_cd: "RMSM000010",
                            supi_menu_cd_nm: "기타 관리",
                            supi_menu_nm: null,
                            childList: null,
                        },
                    ],
                },
            ],
        },
    ],
};
